# Generated by Django 5.0.2 on 2024-02-19 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeMode',
            new_name='TypeModel',
        ),
        migrations.CreateModel(
            name='ClothingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clothing.typemodel')),
            ],
            options={
                'db_table': 'clothes',
            },
        ),
    ]
