# Generated by Django 5.0.2 on 2024-02-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_rename_typemode_typemodel_clothingmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingmodel',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
