# Generated by Django 5.0.2 on 2024-02-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_alter_clothingmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
