# Generated by Django 5.0.2 on 2024-03-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0005_alter_clothingmodel_manufacture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingmodel',
            old_name='manufacture',
            new_name='model',
        ),
    ]
